### ISSUE TITLE
Crear Wiki del proyecto

### ISSUE THREAD

**Issue by Chrisglock** [Ignacio-Gonzalez-C/ProyectoFinal#1]
Se debe crear la Wiki  con la explicación del proyecto.

**Comment by Ignacio-Gonzalez-C** [comment]
Se agregó la base inicial de la Wiki

**Comment by Efocor** [comment]
Se añaden los detalles sobre los comandos de la funcionalidad gráfico lineal

**Comment by Ignacio-Gonzalez-C** [comment]
Se agrega como pagina inicial el proyecto

**Comment by Efocor** [comment]
Se revisan detalles finales. close #1

**Comment by Efocor** [comment]
Se revisan detalles finales. se cierra issue.
